In [41]:
# importing Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import recall_score,confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import  RandomForestClassifier
from sklearn.decomposition import  PCA
from imblearn.combine import  SMOTEENN

import pickle

### Reading the data

In [3]:
df = pd.read_csv('tel_churn.csv')
df=df.drop('Unnamed: 0',axis=1)
df.head(10)

SeniorCitizen  MonthlyCharges  TotalCharges  Churn  gender_Female   
0              0           29.85         29.85      0           True  \
1              0           56.95       1889.50      0          False   
2              0           53.85        108.15      1          False   
3              0           42.30       1840.75      0          False   
4              0           70.70        151.65      1           True   
5              0           99.65        820.50      1           True   
6              0           89.10       1949.40      0          False   
7              0           29.75        301.90      0           True   
8              0          104.80       3046.05      1           True   
9              0           56.15       3487.95      0          False   

   gender_Male  Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  ...   
0        False       False         True           True           False  ...  \
1         True        True        False           True           False  ...   
2         True        True        False           True           False  ...   
3         True        True        False           True           False  ...   
4        False        True        False           True           False  ...   
5        False        True        False           True           False  ...   
6         True        True        False          False            True  ...   
7        False        True        False           True           False  ...   
8        False       False         True           True           False  ...   
9         True        True        False          False            True  ...   

   PaymentMethod_Bank transfer (automatic)   
0                                    False  \
1                                    False   
2                                    False   
3                                     True   
4                                    False   
5                                    False   
6                                    False   
7                                    False   
8                                    False   
9                                     True   

   PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check   
0                                  False                            True  \
1                                  False                           False   
2                                  False                           False   
3                                  False                           False   
4                                  False                            True   
5                                  False                            True   
6                                   True                           False   
7                                  False                           False   
8                                  False                            True   
9                                  False                           False   

   PaymentMethod_Mailed check  tenure_group_1 - 12  tenure_group_13 - 24   
0                       False                 True                 False  \
1                        True                False                 False   
2                        True                 True                 False   
3                       False                False                 False   
4                       False                 True                 False   
5                       False                 True                 False   
6                       False                False                  True   
7                        True                 True                 False   
8                       False                False                 False   
9                       False                False                 False   

   tenure_group_25 - 36  tenure_group_37 - 48  tenure_group_49 - 60   
0                 False                 False                 False  \
1                

In [4]:
x=df.drop('Churn',axis=1)
x

SeniorCitizen  MonthlyCharges  TotalCharges  gender_Female  gender_Male   
0                 0           29.85         29.85           True        False  \
1                 0           56.95       1889.50          False         True   
2                 0           53.85        108.15          False         True   
3                 0           42.30       1840.75          False         True   
4                 0           70.70        151.65           True        False   
...             ...             ...           ...            ...          ...   
7027              0           84.80       1990.50          False         True   
7028              0          103.20       7362.90           True        False   
7029              0           29.60        346.45           True        False   
7030              1           74.40        306.60          False         True   
7031              0          105.65       6844.50          False         True   

      Partner_No  Partner_Yes  Dependents_No  Dependents_Yes  PhoneService_No   
0          False         True           True           False             True  \
1           True        False           True           False            False   
2           True        False           True           False            False   
3           True        False           True           False             True   
4           True        False           True           False            False   
...          ...          ...            ...             ...              ...   
7027       False         True          False            True            False   
7028       False         True          False            True            False   
7029       False         True          False            True             True   
7030       False         True           True           False            False   
7031        True        False           True           False            False   

      ...  PaymentMethod_Bank transfer (automatic)   
0     ...                                    False  \
1     ...                                    False   
2     ...                                    False   
3     ...                                     True   
4     ...                                    False   
...   ...                                      ...   
7027  ...                                    False   
7028  ...                                    False   
7029  ...                                    False   
7030  ...                                    False   
7031  ...                                     True   

      PaymentMethod_Credit card (automatic)  PaymentMethod_Electronic check   
0                                     False                            True  \
1                                     False                           False   
2                                     False                           False   
3                                     False                           False   
4                                     False                            True   
...                                     ...                             ...   
7027                                  False                           False   
7028                                   True                           False   
7029                                  False                            True   
7030                                  False                           False   
7031                                  False                           False   

      PaymentMethod_Mailed check  tenure_group_1 - 12  tenure_group_13 - 24   
0                          False                 True                 False  \
1                           True                False                 False   
2                           True                 True                 False   
3                          False                False                 False   
4                          False                 True              

In [6]:
y=df['Churn']
y

0       0
1       0
2       1
3       0
4       1
       ..
7027    0
7028    0
7029    0
7030    1
7031    0
Name: Churn, Length: 7032, dtype: int64

### Train Test Split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

### Decision Tree Classifier

In [8]:
model_dt=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [9]:
model_dt.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [10]:
y_pred=model_dt.predict(x_test)
y_pred

array([0, 1, 1, ..., 0, 1, 0])

In [11]:
model_dt.score(x_test,y_test)

0.7839374555792467

In [12]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.85      0.86      0.85      1037
           1       0.59      0.57      0.58       370

    accuracy                           0.78      1407
   macro avg       0.72      0.71      0.72      1407
weighted avg       0.78      0.78      0.78      1407



As you can see that the accuracy is quite low, and as it's an imbalanced dataset, we shouldn't consider Accuracy as our metrics to measure the model, as Accuracy is cursed in imbalanced datasets.
Hence, we need to check recall, precision & f1 score for the minority class, and it's quite evident that the precision, recall & f1 score is too low for Class 1, i.e. churned customers.
Hence, moving ahead to call SMOTEENN (UpSampling + ENN)

In [14]:
sm = SMOTEENN()
X_resampled, y_resampled = sm.fit_resample(x,y)

In [15]:
xr_train,xr_test,yr_train,yr_test=train_test_split(X_resampled, y_resampled,test_size=0.2)

In [16]:
model_dt_smote=DecisionTreeClassifier(criterion = "gini",random_state = 100,max_depth=6, min_samples_leaf=8)

In [17]:
model_dt_smote.fit(xr_train,yr_train)
yr_predict = model_dt_smote.predict(xr_test)
model_score_r = model_dt_smote.score(xr_test, yr_test)
print(model_score_r)
print(classification_report(yr_test, yr_predict))

0.9350086655112652
              precision    recall  f1-score   support

           0       0.92      0.93      0.92       495
           1       0.95      0.94      0.94       659

    accuracy                           0.94      1154
   macro avg       0.93      0.93      0.93      1154
weighted avg       0.94      0.94      0.94      1154



In [18]:
print(confusion_matrix(yr_test, yr_predict))

[[459  36]
 [ 39 620]]


### Random Forest Classifier

In [20]:
model_rf=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [21]:
model_rf.fit(x_train,y_train)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [22]:
y_pred=model_rf.predict(x_test)

In [23]:
model_rf.score(x_test,y_test)

0.8052594171997157

In [24]:
print(classification_report(y_test, y_pred, labels=[0,1]))

              precision    recall  f1-score   support

           0       0.83      0.92      0.87      1037
           1       0.68      0.48      0.57       370

    accuracy                           0.81      1407
   macro avg       0.76      0.70      0.72      1407
weighted avg       0.79      0.81      0.79      1407



In [26]:
sm = SMOTEENN()
X_resampled1, y_resampled1 = sm.fit_resample(x,y)

In [27]:
xr_train1,xr_test1,yr_train1,yr_test1=train_test_split(X_resampled1, y_resampled1,test_size=0.2)

In [28]:
model_rf_smote=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [29]:
model_rf_smote.fit(xr_train1,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [30]:
yr_predict1 = model_rf_smote.predict(xr_test1)

In [31]:
model_score_r1 = model_rf_smote.score(xr_test1, yr_test1)

In [32]:
print(model_score_r1)
print(classification_report(yr_test1, yr_predict1))

0.9398814563928873
              precision    recall  f1-score   support

           0       0.96      0.91      0.93       531
           1       0.93      0.97      0.95       650

    accuracy                           0.94      1181
   macro avg       0.94      0.94      0.94      1181
weighted avg       0.94      0.94      0.94      1181



In [33]:
print(confusion_matrix(yr_test1, yr_predict1))

[[481  50]
 [ 21 629]]


With RF Classifier, also we are able to get quite good results, infact better than Decision Tree.


### Performing PCA

In [35]:
pca = PCA(0.9)
xr_train_pca = pca.fit_transform(xr_train1)
xr_test_pca = pca.transform(xr_test1)
explained_variance = pca.explained_variance_ratio_

In [36]:
model=RandomForestClassifier(n_estimators=100, criterion='gini', random_state = 100,max_depth=6, min_samples_leaf=8)

In [37]:
model.fit(xr_train_pca,yr_train1)

RandomForestClassifier(max_depth=6, min_samples_leaf=8, random_state=100)

In [38]:
yr_predict_pca = model.predict(xr_test_pca)

In [39]:
model_score_r_pca = model.score(xr_test_pca, yr_test1)

In [40]:
print(model_score_r_pca)
print(classification_report(yr_test1, yr_predict_pca))

0.7341236240474175
              precision    recall  f1-score   support

           0       0.77      0.59      0.67       531
           1       0.72      0.85      0.78       650

    accuracy                           0.73      1181
   macro avg       0.74      0.72      0.72      1181
weighted avg       0.74      0.73      0.73      1181



With PCA, we couldn't see any better results, hence let's finalise the model which was created by RF Classifier, and save the model so that we can use it in a later stage :)

### Pickling the model

In [42]:
filename = 'model.sav'

In [43]:
pickle.dump(model_rf_smote, open(filename, 'wb'))

In [44]:
load_model = pickle.load(open(filename, 'rb'))

In [45]:
model_score_r1 = load_model.score(xr_test1, yr_test1)

In [46]:
model_score_r1

0.9398814563928873

Our final model i.e. RF Classifier with SMOTEENN, is now ready and dumped in model.sav, which we will use and prepare API's so that we can access our model from UI.